[2023-06-29T19:48:01.628+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_igbe_data.request_data manual__2023-06-29T15:47:46-04:00 [queued]>
[2023-06-29T19:48:01.671+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_igbe_data.request_data manual__2023-06-29T15:47:46-04:00 [queued]>
[2023-06-29T19:48:01.671+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-29T19:48:01.672+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-29T19:48:01.672+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-29T19:48:01.749+0000] {taskinstance.py:1309} INFO - Executing <Task(SimpleHttpOperator): request_data> on 2023-06-29 19:47:46+00:00
[2023-06-29T19:48:01.757+0000] {standard_task_runner.py:55} INFO - Started process 454 to run task
[2023-06-29T19:48:01.763+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_igbe_data', 'request_data', 'manual__2023-06-29T15:47:46-04:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_ibge_data.py', '--cfg-path', '/tmp/tmp8wx35rbg']
[2023-06-29T19:48:01.765+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask request_data
[2023-06-29T19:48:02.210+0000] {task_command.py:389} INFO - Running <TaskInstance: get_igbe_data.request_data manual__2023-06-29T15:47:46-04:00 [running]> on host b4b1b6c8b5f0
[2023-06-29T19:48:02.436+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_igbe_data
AIRFLOW_CTX_TASK_ID=request_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-29T19:47:46+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-29T15:47:46-04:00
[2023-06-29T19:48:02.437+0000] {http.py:123} INFO - Calling HTTP method
[2023-06-29T19:48:02.472+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 125, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 137, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 91, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `ibge_api` isn't defined
[2023-06-29T19:48:02.508+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_igbe_data, task_id=request_data, execution_date=20230629T194746, start_date=20230629T194801, end_date=20230629T194802
[2023-06-29T19:48:02.600+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task request_data (The conn_id `ibge_api` isn't defined; 454)
[2023-06-29T19:48:02.658+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-29T19:48:02.833+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
