[2023-06-27T15:31:20.916+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-27T11:30:43-04:00 [queued]>
[2023-06-27T15:31:20.927+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-27T11:30:43-04:00 [queued]>
[2023-06-27T15:31:20.927+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T15:31:20.928+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-27T15:31:20.928+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T15:31:20.969+0000] {taskinstance.py:1309} INFO - Executing <Task(S3ToSqlOperator): transfer_s3_to_rds> on 2023-06-27 15:30:43+00:00
[2023-06-27T15:31:20.977+0000] {standard_task_runner.py:55} INFO - Started process 4380 to run task
[2023-06-27T15:31:20.982+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'transfer_s3_to_rds', 'manual__2023-06-27T11:30:43-04:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmpytd5ng0v']
[2023-06-27T15:31:20.984+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask transfer_s3_to_rds
[2023-06-27T15:31:21.071+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-27T11:30:43-04:00 [running]> on host fef15d81d3ea
[2023-06-27T15:31:21.212+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=transfer_s3_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-06-27T15:30:43+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-27T11:30:43-04:00
[2023-06-27T15:31:21.213+0000] {s3_to_sql.py:101} INFO - Loading testfiles/processed/processed_data_pnadc_2023_06_27.csv to SQL table people_info...
[2023-06-27T15:31:21.222+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-06-27T15:31:21.223+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-06-27T15:31:24.858+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-27T15:31:25.166+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-27T15:31:26.790+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/s3_to_sql.py", line 117, in execute
    commit_every=self.commit_every,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 453, in insert_rows
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "dbpeopleall.ci6rlhbtdtag.us-east-1.rds.amazonaws.com" (3.216.76.66), port 5432 failed: FATAL:  database "postgres_root" does not exist

[2023-06-27T15:31:26.799+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_pnadc_data_new, task_id=transfer_s3_to_rds, execution_date=20230627T153043, start_date=20230627T153120, end_date=20230627T153126
[2023-06-27T15:31:26.842+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 59 for task transfer_s3_to_rds (connection to server at "dbpeopleall.ci6rlhbtdtag.us-east-1.rds.amazonaws.com" (3.216.76.66), port 5432 failed: FATAL:  database "postgres_root" does not exist
; 4380)
[2023-06-27T15:31:26.864+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-27T15:31:26.890+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
