[2023-06-27T20:22:34.206+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.generate_filter_data manual__2023-06-27T16:20:49-04:00 [queued]>
[2023-06-27T20:22:34.216+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.generate_filter_data manual__2023-06-27T16:20:49-04:00 [queued]>
[2023-06-27T20:22:34.216+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T20:22:34.216+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-27T20:22:34.217+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T20:22:34.274+0000] {taskinstance.py:1309} INFO - Executing <Task(SqlToS3Operator): generate_filter_data> on 2023-06-27 20:20:49+00:00
[2023-06-27T20:22:34.280+0000] {standard_task_runner.py:55} INFO - Started process 24522 to run task
[2023-06-27T20:22:34.283+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'generate_filter_data', 'manual__2023-06-27T16:20:49-04:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmp35iabbxg']
[2023-06-27T20:22:34.284+0000] {standard_task_runner.py:83} INFO - Job 107: Subtask generate_filter_data
[2023-06-27T20:22:34.367+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.generate_filter_data manual__2023-06-27T16:20:49-04:00 [running]> on host fef15d81d3ea
[2023-06-27T20:22:34.539+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=generate_filter_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-27T20:20:49+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-27T16:20:49-04:00
[2023-06-27T20:22:34.549+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-27T20:22:34.762+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-27T20:22:36.889+0000] {sql_to_s3.py:168} INFO - Data from SQL obtained
[2023-06-27T20:22:36.891+0000] {sql_to_s3.py:175} INFO - Writing data to temp file
[2023-06-27T20:22:36.892+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/sql_to_s3.py", line 176, in execute
    getattr(data_df, file_options.function)(tmp_file.name, **self.pd_kwargs)
TypeError: to_csv() got an unexpected keyword argument 'delimiter'
[2023-06-27T20:22:37.106+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_pnadc_data_new, task_id=generate_filter_data, execution_date=20230627T202049, start_date=20230627T202234, end_date=20230627T202237
[2023-06-27T20:22:37.155+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 107 for task generate_filter_data (to_csv() got an unexpected keyword argument 'delimiter'; 24522)
[2023-06-27T20:22:37.196+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-27T20:22:37.224+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
