[2023-06-28T04:17:20.214+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-28T00:16:40-04:00 [queued]>
[2023-06-28T04:17:20.225+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-28T00:16:40-04:00 [queued]>
[2023-06-28T04:17:20.225+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T04:17:20.225+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-28T04:17:20.226+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T04:17:20.274+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): transfer_s3_to_rds> on 2023-06-28 04:16:40+00:00
[2023-06-28T04:17:20.284+0000] {standard_task_runner.py:55} INFO - Started process 23938 to run task
[2023-06-28T04:17:20.289+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'transfer_s3_to_rds', 'manual__2023-06-28T00:16:40-04:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmpnf2sp32g']
[2023-06-28T04:17:20.298+0000] {standard_task_runner.py:83} INFO - Job 209: Subtask transfer_s3_to_rds
[2023-06-28T04:17:20.451+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-28T00:16:40-04:00 [running]> on host 8b415078c232
[2023-06-28T04:17:20.867+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=transfer_s3_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T04:16:40+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-28T00:16:40-04:00
[2023-06-28T04:17:20.900+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-06-28T04:17:20.901+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-06-28T04:17:22.666+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-28T04:17:24.591+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/send.py", line 37, in _send_from_s3_to_rds
    method=method
TypeError: to_sql() got an unexpected keyword argument 'table'
[2023-06-28T04:17:24.612+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_pnadc_data_new, task_id=transfer_s3_to_rds, execution_date=20230628T041640, start_date=20230628T041720, end_date=20230628T041724
[2023-06-28T04:17:24.665+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 209 for task transfer_s3_to_rds (to_sql() got an unexpected keyword argument 'table'; 23938)
[2023-06-28T04:17:24.707+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-28T04:17:24.735+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
