[2023-06-27T15:17:12.434+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T11:17:07-04:00 [queued]>
[2023-06-27T15:17:12.447+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T11:17:07-04:00 [queued]>
[2023-06-27T15:17:12.447+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T15:17:12.447+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-27T15:17:12.447+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T15:17:12.519+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_mongodb_data> on 2023-06-27 15:17:07+00:00
[2023-06-27T15:17:12.526+0000] {standard_task_runner.py:55} INFO - Started process 3194 to run task
[2023-06-27T15:17:12.530+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'get_mongodb_data', 'manual__2023-06-27T11:17:07-04:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmpbqwtsgyx']
[2023-06-27T15:17:12.533+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask get_mongodb_data
[2023-06-27T15:17:12.645+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T11:17:07-04:00 [running]> on host fef15d81d3ea
[2023-06-27T15:17:12.821+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=get_mongodb_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-27T15:17:07+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-27T11:17:07-04:00
[2023-06-27T15:17:12.834+0000] {base.py:73} INFO - Using connection ID 'mongodb_conn' for task execution.
[2023-06-27T15:17:15.645+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/extract.py", line 18, in _get_mongodb_data
    with open(path_to_save,'x') as f:
FileExistsError: [Errno 17] File exists: '/tmp/pnadc_data_2023_06_27.json'
[2023-06-27T15:17:15.656+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_pnadc_data_new, task_id=get_mongodb_data, execution_date=20230627T151707, start_date=20230627T151712, end_date=20230627T151715
[2023-06-27T15:17:15.816+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task get_mongodb_data ([Errno 17] File exists: '/tmp/pnadc_data_2023_06_27.json'; 3194)
[2023-06-27T15:17:15.843+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-27T15:17:15.887+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
