[2023-06-28T21:04:21.791+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.cleans.clean_data_mod_rows manual__2023-06-28T17:03:57-04:00 [queued]>
[2023-06-28T21:04:21.801+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.cleans.clean_data_mod_rows manual__2023-06-28T17:03:57-04:00 [queued]>
[2023-06-28T21:04:21.802+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T21:04:21.802+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-28T21:04:21.802+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T21:04:21.897+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): cleans.clean_data_mod_rows> on 2023-06-28 21:03:57+00:00
[2023-06-28T21:04:21.917+0000] {standard_task_runner.py:55} INFO - Started process 609 to run task
[2023-06-28T21:04:21.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'cleans.clean_data_mod_rows', 'manual__2023-06-28T17:03:57-04:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmp95tvq41n']
[2023-06-28T21:04:21.932+0000] {standard_task_runner.py:83} INFO - Job 260: Subtask cleans.clean_data_mod_rows
[2023-06-28T21:04:22.041+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.cleans.clean_data_mod_rows manual__2023-06-28T17:03:57-04:00 [running]> on host d9b032dfc97f
[2023-06-28T21:04:22.618+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=cleans.clean_data_mod_rows
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T21:03:57+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-28T17:03:57-04:00
[2023-06-28T21:04:22.621+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/transform.py", line 48, in _clean_rows
    df = pd.read_csv(path_to_data,na_filter=False,decimal=None)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 415, in pandas._libs.parsers.TextReader.__cinit__
TypeError: object of type 'NoneType' has no len()
[2023-06-28T21:04:22.631+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_pnadc_data_new, task_id=cleans.clean_data_mod_rows, execution_date=20230628T210357, start_date=20230628T210421, end_date=20230628T210422
[2023-06-28T21:04:22.689+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 260 for task cleans.clean_data_mod_rows (object of type 'NoneType' has no len(); 609)
[2023-06-28T21:04:22.743+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-28T21:04:22.834+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
